/**
 * Cloudflare Worker entrypoint (wrangler.jsonc -> "main").
 *
 * - `fetch`     : the whole Next.js app, produced by `opennextjs-cloudflare build`.
 * - `scheduled` : the hourly Cron Trigger. Refreshes cached YouTube stats for
 *                 channels stored in D1 so page views never hit the YouTube API.
 */
// @ts-ignore — generated by `opennextjs-cloudflare build`; not present until then.
import openNextWorker from './.open-next/worker.js';
import type { D1Database, ExportedHandler, ScheduledController, ExecutionContext } from '@cloudflare/workers-types';
import { setDatabase } from './lib/db';
import { refreshAllChannelStats } from './lib/refresh-service';

interface Env {
  DB: D1Database;
  YOUTUBE_API_KEY?: string;
}

const handler = {
  fetch: openNextWorker.fetch,

  async scheduled(_controller: ScheduledController, env: Env, ctx: ExecutionContext) {
    ctx.waitUntil(
      (async () => {
        if (!env.YOUTUBE_API_KEY) {
          console.log('[cron] YOUTUBE_API_KEY not set — skipping stats refresh.');
          return;
        }
        setDatabase(env.DB);
        const result = await refreshAllChannelStats(env.YOUTUBE_API_KEY, { log: (m) => console.log(`[cron] ${m}`) });
        console.log(`[cron] stats refresh done: ${result.updated} updated, ${result.failed} failed`);
      })()
    );
  },
} satisfies ExportedHandler<Env>;

export default handler;
