// Cloudflare Worker entrypoint.
//
// Wraps the Worker that OpenNext generates (which serves the whole Next.js
// app) and adds a `scheduled` handler for the Cron Trigger in wrangler.toml.
// wrangler.toml points `main` at this file; `npm run cf:build` produces
// ./.open-next/worker.js first.

// @ts-ignore — generated by `opennextjs-cloudflare build`, absent until then.
import openNextWorker from './.open-next/worker.js';
import { d1Adapter, setDb, type D1Like } from './db';
import { refreshChannelStats } from './lib/stats-refresh';
import { rebuildRankCache } from './lib/leaderboard-service';

interface Env {
  DB: D1Like;
  [key: string]: unknown;
}

// Keep well inside the YouTube Data API free quota (10,000 units/day):
// 1 unit per channel * 40 channels * 24 runs = 960 units/day.
const CHANNELS_PER_RUN = 40;

export default {
  fetch: (openNextWorker as { fetch: (...args: unknown[]) => unknown }).fetch,

  async scheduled(_event: unknown, env: Env, ctx: { waitUntil(p: Promise<unknown>): void }) {
    ctx.waitUntil(
      (async () => {
        setDb(d1Adapter(env.DB));
        try {
          await rebuildRankCache();
          if (process.env.YOUTUBE_API_KEY) {
            const res = await refreshChannelStats(d1Adapter(env.DB), { limit: CHANNELS_PER_RUN });
            console.log(`[cron] stats refresh: ${res.updated} updated, ${res.failed} failed`);
          }
        } catch (e) {
          console.error('[cron] failed', e);
        } finally {
          setDb(null);
        }
      })()
    );
  },
};
