/**
 * One-time import: copies every real row out of the OLD local SQLite file
 * (better-sqlite3, from the pre-D1 version of this app — db/index.ts /
 * db/schema.sql, since removed) into a .sql file you load into Cloudflare
 * D1. Not part of the running app; run it once, then throw it away.
 *
 * The old schema.sql and migrations/0001_initial.sql are the same schema,
 * so this is a straight copy — no column mapping needed.
 *
 * Usage:
 *   npx tsx scripts/migrate-sqlite-to-d1.ts path/to/old/data/app.db > import.sql
 *
 * Then load it into D1:
 *   npx wrangler d1 execute DB --local  --file=import.sql   # test first
 *   npx wrangler d1 execute DB --remote --file=import.sql   # then production
 *
 * Safe to re-run: every statement is `INSERT OR IGNORE`, keyed on each
 * table's primary key, so loading the same import.sql twice does nothing
 * the second time rather than erroring or duplicating rows.
 *
 * Deliberately NOT migrated:
 *   - presence_pings   — live "who's online now" data; meaningless to carry
 *                        over, and expires within a minute anyway.
 *   - categories / countries — fixed reference lists the schema already
 *                        seeds; only copied if your old file has ones the
 *                        new schema doesn't (a category you added by hand).
 */
import Database from 'better-sqlite3';
import path from 'node:path';

const oldDbPath = process.argv[2];
if (!oldDbPath) {
  console.error('Usage: npx tsx scripts/migrate-sqlite-to-d1.ts path/to/old/data/app.db > import.sql');
  process.exit(1);
}

const db = new Database(path.resolve(oldDbPath), { readonly: true, fileMustExist: true });

function sqlLiteral(v: unknown): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (Buffer.isBuffer(v)) return `X'${v.toString('hex')}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

function tableExists(name: string): boolean {
  return !!db.prepare(`SELECT 1 FROM sqlite_master WHERE type='table' AND name=?`).get(name);
}

function dumpTable(name: string): string[] {
  if (!tableExists(name)) {
    console.error(`-- skipping ${name}: table not found in old database`);
    return [];
  }
  const rows = db.prepare(`SELECT * FROM ${name}`).all() as Record<string, unknown>[];
  if (rows.length === 0) return [];
  const columns = Object.keys(rows[0]);
  return rows.map(
    (row) =>
      `INSERT OR IGNORE INTO ${name} (${columns.join(', ')}) VALUES (${columns
        .map((c) => sqlLiteral(row[c]))
        .join(', ')});`
  );
}

// Insertion order respects every FK in migrations/0001_initial.sql —
// a table only appears after every table it references.
const TABLES_IN_FK_ORDER = [
  'categories',
  'countries',
  'users',
  'channels',
  'channel_stats',
  'listings',
  'payments',
  'bids',
  'channel_ownership_tokens',
  'rank_history',
  'profile_views',
  'youtube_clicks',
  'reports',
  'admin_actions',
  'notifications',
  'settings',
];

const statements: string[] = [
  '-- Generated by scripts/migrate-sqlite-to-d1.ts — import once, then discard.',
  'PRAGMA defer_foreign_keys = TRUE;', // lets rows load even if an FK target appears later in this same file
];

let totalRows = 0;
for (const table of TABLES_IN_FK_ORDER) {
  const rows = dumpTable(table);
  if (rows.length === 0) continue;
  statements.push(`\n-- ${table} (${rows.length} rows)`);
  statements.push(...rows);
  totalRows += rows.length;
}

console.log(statements.join('\n'));
console.error(`\nWrote ${totalRows} rows across ${TABLES_IN_FK_ORDER.length} tables to stdout.`);
